name: dispml
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=gpu_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=py312h06a4308_0
  - chardet=5.2.0=py312h7900ff3_1
  - contourpy=1.2.0=py312h8572e83_0
  - cuda-version=12.3=h32bc705_2
  - cycler=0.12.1=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.49.0=py312h98912ed_0
  - freetype=2.12.1=h267a509_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - greenlet=3.0.3=py312h30efb56_0
  - icu=73.2=h59595ed_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - kiwisolver=1.4.5=py312h8572e83_1
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=21_linux64_openblas
  - libboost=1.82.0=h6fcfa73_6
  - libboost-python=1.82.0=py312hfb10629_6
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=21_linux64_openblas
  - libdeflate=1.19=hd590300_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.3=h783c2da_0
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=21_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libpng=1.6.42=h2797004_0
  - libsqlite=3.45.1=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.6.0=ha9c0a0a_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxgboost=2.0.3=cuda120_h75debf4_1
  - libzlib=1.2.13=hd590300_5
  - matplotlib-base=3.8.3=py312he5832f3_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nccl=2.20.3.1=h3a97aeb_0
  - ncurses=6.4=h59595ed_2
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=1.26.4=py312heda63a1_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=3.2.1=hd590300_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.2.0=py312hfb8ada1_0
  - pcre2=10.42=hcad00b1_0
  - pillow=10.2.0=py312hf3581a9_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-xgboost=2.0.3=cuda118_pyhedeaf28_1
  - pycairo=1.26.0=py312he48a392_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=4_cp312
  - pytz=2024.1=pyhd8ed1ab_0
  - rdkit=2023.09.5=py312hd93e07f_0
  - readline=8.2=h8228510_1
  - reportlab=4.1.0=py312h98912ed_0
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - scikit-learn=1.4.1.post1=py312h394d371_0
  - scipy=1.12.0=py312heda63a1_2
  - setuptools=69.0.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=2.0.27=py312h98912ed_0
  - threadpoolctl=3.3.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - typing-extensions=4.9.0=hd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xgboost=2.0.3=cuda118_pyh5ebfdf7_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xyz2mol=0.1.2=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
prefix: /home/corev/miniconda3/envs/dispml
